## NumPy Tutorial

In [1]:
import numpy as np

### Array Types - 1D, 2D, 3D 

In [8]:
#1 Dimentional array
myArray = np.array([2, 3, 4])
myArray

array([2, 3, 4])

In [9]:
#2 Dimentional array
array2 = np.array([2,3,4,5,6,2]).reshape(2,3)
array2

array([[2, 3, 4],
       [5, 6, 2]])

In [10]:
#3 Dimentional array
array3 = np.array([1,2,3,4,5,6,7,8]).reshape(2,2,2)
array3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### NumPy Calculation Basics

In [12]:
a = np.array([1,2,3,4,5,6])
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())

21
1
6
3.5


### Special case Arrays

In [13]:
np.zeros(5) # Creates an array of zeros with 5 elements
np.linspace(0, 6, 10) # Creates an array of values from 0 through 6 in 10 even spaces
np.random.rand(3) # Three random values between 0 and 1
np.random.randint(1, 1000) # A random integer between 1 and 1000
np.arange(25) # Like the "Range" function we learned earlier, this is gives you a range of integers between 1 - 25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])